version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: shop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
